### ISSUE TITLE
Running Speed for Windows Caffe

### ISSUE THREAD

**Issue by jiamings** [niuzhiheng/caffe#27]
Hello,
I tested on the **CIFAR10 dataset** with your version of Windows Caffe, and it turns out that the **full solver**(60000 iterations) took **several hours** to complete(more than 6 hours), much slower than I had expected.
I would like to know whether it is a hardware issue, so could you please tell me how long this training took on your machine? Thanks!

**Comment by zichun-h** [comment]
Hello,
I 'm sorry to tell you that I'm not niuzhiheng/caffe.‍
Maybe you should send the email to the real author. And I wonder why you sent the email to this address.
Good luck!

------------------ 原始邮件 ------------------ 
发件人: "Jiaming Song";notifications@github.com;
发送时间: 2014年8月13日(星期三) 下午5:08
收件人: "niuzhiheng/caffe"caffe@noreply.github.com; 

主题: [caffe] Running Speed for Windows Caffe (#27)

Hello,
 I tested on the CIFAR10 dataset with your version of Windows Caffe, and it turns out that the full solver(60000 iterations) took several hours to complete(more than 6 hours), much slower than I had expected.
 I would like to know whether it is a hardware issue, so could you please tell me how long this training took on your machine? Thanks!

**Comment by niuzhiheng** [comment]
@zichun-h You received the email because you stared this project on github. You may unstart this project or unsubscribe the notification from [this page](https://github.com/niuzhiheng/caffe/issues/27).
